"""Typed fields of the provider-SDK models the loop reads — GENERATED, do not edit.

Rendered by ``scripts/gen_sdk_shapes.py`` from openai 2.24.0 and anthropic 0.87.0;
``tests/agent/transports/test_sdk_shapes_fresh.py`` re-renders and diffs.

``KINDS``: model -> field -> ``None`` (a scalar or an untyped value, kept as sent) or
``(target, arity)`` where target is a model or ``union:<name>`` and arity ``one`` / ``list``.
``UNIONS``: union -> discriminator (``type``) value -> model; an unknown value builds the FIRST
model, as the SDKs' ``construct_type`` does. ``ALIASES``: model -> wire key -> attribute name.
``ROOTS``: what each wire returns.
"""

# fmt: off
ROOTS = {'chat.completion': 'openai.ChatCompletion', 'chat.completion.chunk': 'openai.ChatCompletionChunk', 'anthropic.message': 'anthropic.Message', 'anthropic.parsed_message': 'anthropic.ParsedMessage', 'anthropic.content_block': 'union:anthropic.Message.content', 'anthropic.raw_event': 'union:anthropic.raw_event', 'anthropic.stream_event': 'union:anthropic.stream_event', 'responses.response': 'openai.Response', 'responses.event': 'union:responses.event'}

KINDS = {
    'anthropic.Base64PDFSource': {'data': None, 'media_type': None, 'type': None},
    'anthropic.BashCodeExecutionOutputBlock': {'file_id': None, 'type': None},
    'anthropic.BashCodeExecutionResultBlock': {'content': ('anthropic.BashCodeExecutionOutputBlock', 'list'), 'return_code': None, 'stderr': None, 'stdout': None, 'type': None},
    'anthropic.BashCodeExecutionToolResultBlock': {'content': ('union:anthropic.BashCodeExecutionToolResultBlock.content', 'one'), 'tool_use_id': None, 'type': None},
    'anthropic.BashCodeExecutionToolResultError': {'error_code': None, 'type': None},
    'anthropic.CacheCreation': {'ephemeral_1h_input_tokens': None, 'ephemeral_5m_input_tokens': None},
    'anthropic.CitationCharLocation': {'cited_text': None, 'document_index': None, 'document_title': None, 'end_char_index': None, 'file_id': None, 'start_char_index': None, 'type': None},
    'anthropic.CitationContentBlockLocation': {'cited_text': None, 'document_index': None, 'document_title': None, 'end_block_index': None, 'file_id': None, 'start_block_index': None, 'type': None},
    'anthropic.CitationEvent': {'type': None, 'citation': ('union:anthropic.TextBlock.citations', 'one'), 'snapshot': ('union:anthropic.TextBlock.citations', 'list')},
    'anthropic.CitationPageLocation': {'cited_text': None, 'document_index': None, 'document_title': None, 'end_page_number': None, 'file_id': None, 'start_page_number': None, 'type': None},
    'anthropic.CitationsConfig': {'enabled': None},
    'anthropic.CitationsDelta': {'citation': ('union:anthropic.TextBlock.citations', 'one'), 'type': None},
    'anthropic.CitationsSearchResultLocation': {'cited_text': None, 'end_block_index': None, 'search_result_index': None, 'source': None, 'start_block_index': None, 'title': None, 'type': None},
    'anthropic.CitationsWebSearchResultLocation': {'cited_text': None, 'encrypted_index': None, 'title': None, 'type': None, 'url': None},
    'anthropic.CodeExecutionOutputBlock': {'file_id': None, 'type': None},
    'anthropic.CodeExecutionResultBlock': {'content': ('anthropic.CodeExecutionOutputBlock', 'list'), 'return_code': None, 'stderr': None, 'stdout': None, 'type': None},
    'anthropic.CodeExecutionToolResultBlock': {'content': ('union:anthropic.CodeExecutionToolResultBlock.content', 'one'), 'tool_use_id': None, 'type': None},
    'anthropic.CodeExecutionToolResultError': {'error_code': None, 'type': None},
    'anthropic.Container': {'id': None, 'expires_at': None},
    'anthropic.ContainerUploadBlock': {'file_id': None, 'type': None},
    'anthropic.Delta': {'container': ('anthropic.Container', 'one'), 'stop_reason': None, 'stop_sequence': None},
    'anthropic.DirectCaller': {'type': None},
    'anthropic.DocumentBlock': {'citations': ('anthropic.CitationsConfig', 'one'), 'source': ('union:anthropic.DocumentBlock.source', 'one'), 'title': None, 'type': None},
    'anthropic.EncryptedCodeExecutionResultBlock': {'content': ('anthropic.CodeExecutionOutputBlock', 'list'), 'encrypted_stdout': None, 'return_code': None, 'stderr': None, 'type': None},
    'anthropic.InputJSONDelta': {'partial_json': None, 'type': None},
    'anthropic.InputJsonEvent': {'type': None, 'partial_json': None, 'snapshot': None},
    'anthropic.Message': {'id': None, 'container': ('anthropic.Container', 'one'), 'content': ('union:anthropic.Message.content', 'list'), 'model': None, 'role': None, 'stop_reason': None, 'stop_sequence': None, 'type': None, 'usage': ('anthropic.Usage', 'one')},
    'anthropic.MessageDeltaUsage': {'cache_creation_input_tokens': None, 'cache_read_input_tokens': None, 'input_tokens': None, 'output_tokens': None, 'server_tool_use': ('anthropic.ServerToolUsage', 'one')},
    'anthropic.ParsedContentBlockStopEvent': {'index': None, 'type': None, 'content_block': ('union:anthropic.ParsedMessage.content', 'one')},
    'anthropic.ParsedMessage': {'id': None, 'container': ('anthropic.Container', 'one'), 'content': ('union:anthropic.ParsedMessage.content', 'list'), 'model': None, 'role': None, 'stop_reason': None, 'stop_sequence': None, 'type': None, 'usage': ('anthropic.Usage', 'one')},
    'anthropic.ParsedMessageStopEvent': {'type': None, 'message': ('anthropic.ParsedMessage_TypeVar', 'one')},
    'anthropic.ParsedMessage_TypeVar': {'id': None, 'container': ('anthropic.Container', 'one'), 'content': ('union:anthropic.ParsedMessage_TypeVar.content', 'list'), 'model': None, 'role': None, 'stop_reason': None, 'stop_sequence': None, 'type': None, 'usage': ('anthropic.Usage', 'one')},
    'anthropic.ParsedTextBlock': {'citations': ('union:anthropic.TextBlock.citations', 'list'), 'text': None, 'type': None, 'parsed_output': None},
    'anthropic.ParsedTextBlock_TypeVar': {'citations': ('union:anthropic.TextBlock.citations', 'list'), 'text': None, 'type': None, 'parsed_output': None},
    'anthropic.PlainTextSource': {'data': None, 'media_type': None, 'type': None},
    'anthropic.RawContentBlockDeltaEvent': {'delta': ('union:anthropic.RawContentBlockDeltaEvent.delta', 'one'), 'index': None, 'type': None},
    'anthropic.RawContentBlockStartEvent': {'content_block': ('union:anthropic.Message.content', 'one'), 'index': None, 'type': None},
    'anthropic.RawContentBlockStopEvent': {'index': None, 'type': None},
    'anthropic.RawMessageDeltaEvent': {'delta': ('anthropic.Delta', 'one'), 'type': None, 'usage': ('anthropic.MessageDeltaUsage', 'one')},
    'anthropic.RawMessageStartEvent': {'message': ('anthropic.Message', 'one'), 'type': None},
    'anthropic.RawMessageStopEvent': {'type': None},
    'anthropic.RedactedThinkingBlock': {'data': None, 'type': None},
    'anthropic.ServerToolCaller': {'tool_id': None, 'type': None},
    'anthropic.ServerToolCaller20260120': {'tool_id': None, 'type': None},
    'anthropic.ServerToolUsage': {'web_fetch_requests': None, 'web_search_requests': None},
    'anthropic.ServerToolUseBlock': {'id': None, 'caller': ('union:anthropic.ToolUseBlock.caller', 'one'), 'input': None, 'name': None, 'type': None},
    'anthropic.SignatureDelta': {'signature': None, 'type': None},
    'anthropic.SignatureEvent': {'type': None, 'signature': None},
    'anthropic.TextBlock': {'citations': ('union:anthropic.TextBlock.citations', 'list'), 'text': None, 'type': None},
    'anthropic.TextDelta': {'text': None, 'type': None},
    'anthropic.TextEditorCodeExecutionCreateResultBlock': {'is_file_update': None, 'type': None},
    'anthropic.TextEditorCodeExecutionStrReplaceResultBlock': {'lines': None, 'new_lines': None, 'new_start': None, 'old_lines': None, 'old_start': None, 'type': None},
    'anthropic.TextEditorCodeExecutionToolResultBlock': {'content': ('union:anthropic.TextEditorCodeExecutionToolResultBlock.content', 'one'), 'tool_use_id': None, 'type': None},
    'anthropic.TextEditorCodeExecutionToolResultError': {'error_code': None, 'error_message': None, 'type': None},
    'anthropic.TextEditorCodeExecutionViewResultBlock': {'content': None, 'file_type': None, 'num_lines': None, 'start_line': None, 'total_lines': None, 'type': None},
    'anthropic.TextEvent': {'type': None, 'text': None, 'snapshot': None},
    'anthropic.ThinkingBlock': {'signature': None, 'thinking': None, 'type': None},
    'anthropic.ThinkingDelta': {'thinking': None, 'type': None},
    'anthropic.ThinkingEvent': {'type': None, 'thinking': None, 'snapshot': None},
    'anthropic.ToolReferenceBlock': {'tool_name': None, 'type': None},
    'anthropic.ToolSearchToolResultBlock': {'content': ('union:anthropic.ToolSearchToolResultBlock.content', 'one'), 'tool_use_id': None, 'type': None},
    'anthropic.ToolSearchToolResultError': {'error_code': None, 'error_message': None, 'type': None},
    'anthropic.ToolSearchToolSearchResultBlock': {'tool_references': ('anthropic.ToolReferenceBlock', 'list'), 'type': None},
    'anthropic.ToolUseBlock': {'id': None, 'caller': ('union:anthropic.ToolUseBlock.caller', 'one'), 'input': None, 'name': None, 'type': None},
    'anthropic.Usage': {'cache_creation': ('anthropic.CacheCreation', 'one'), 'cache_creation_input_tokens': None, 'cache_read_input_tokens': None, 'inference_geo': None, 'input_tokens': None, 'output_tokens': None, 'server_tool_use': ('anthropic.ServerToolUsage', 'one'), 'service_tier': None},
    'anthropic.WebFetchBlock': {'content': ('anthropic.DocumentBlock', 'one'), 'retrieved_at': None, 'type': None, 'url': None},
    'anthropic.WebFetchToolResultBlock': {'caller': ('union:anthropic.ToolUseBlock.caller', 'one'), 'content': ('union:anthropic.WebFetchToolResultBlock.content', 'one'), 'tool_use_id': None, 'type': None},
    'anthropic.WebFetchToolResultErrorBlock': {'error_code': None, 'type': None},
    'anthropic.WebSearchResultBlock': {'encrypted_content': None, 'page_age': None, 'title': None, 'type': None, 'url': None},
    'anthropic.WebSearchToolResultBlock': {'caller': ('union:anthropic.ToolUseBlock.caller', 'one'), 'content': ('anthropic.WebSearchResultBlock', 'list'), 'tool_use_id': None, 'type': None},
    'openai.Action': {'commands': None, 'max_output_length': None, 'timeout_ms': None},
    'openai.ActionClick': {'button': None, 'type': None, 'x': None, 'y': None},
    'openai.ActionDoubleClick': {'type': None, 'x': None, 'y': None},
    'openai.ActionDrag': {'path': ('openai.ActionDragPath', 'list'), 'type': None},
    'openai.ActionDragPath': {'x': None, 'y': None},
    'openai.ActionFind': {'pattern': None, 'type': None, 'url': None},
    'openai.ActionKeypress': {'keys': None, 'type': None},
    'openai.ActionMove': {'type': None, 'x': None, 'y': None},
    'openai.ActionOpenPage': {'type': None, 'url': None},
    'openai.ActionScreenshot': {'type': None},
    'openai.ActionScroll': {'scroll_x': None, 'scroll_y': None, 'type': None, 'x': None, 'y': None},
    'openai.ActionSearch': {'query': None, 'type': None, 'queries': None, 'sources': ('openai.ActionSearchSource', 'list')},
    'openai.ActionSearchSource': {'type': None, 'url': None},
    'openai.ActionType': {'text': None, 'type': None},
    'openai.ActionWait': {'type': None},
    'openai.Annotation': {'type': None, 'url_citation': ('openai.AnnotationURLCitation', 'one')},
    'openai.AnnotationContainerFileCitation': {'container_id': None, 'end_index': None, 'file_id': None, 'filename': None, 'start_index': None, 'type': None},
    'openai.AnnotationFileCitation': {'file_id': None, 'filename': None, 'index': None, 'type': None},
    'openai.AnnotationFilePath': {'file_id': None, 'index': None, 'type': None},
    'openai.AnnotationURLCitation': {'end_index': None, 'start_index': None, 'title': None, 'url': None},
    'openai.AnnotationURLCitation@response_output_text': {'end_index': None, 'start_index': None, 'title': None, 'type': None, 'url': None},
    'openai.ApplyPatchTool': {'type': None},
    'openai.ChatCompletion': {'id': None, 'choices': ('openai.Choice', 'list'), 'created': None, 'model': None, 'object': None, 'service_tier': None, 'system_fingerprint': None, 'usage': ('openai.CompletionUsage', 'one')},
    'openai.ChatCompletionAudio': {'id': None, 'data': None, 'expires_at': None, 'transcript': None},
    'openai.ChatCompletionChunk': {'id': None, 'choices': ('openai.Choice@chat_completion_chunk', 'list'), 'created': None, 'model': None, 'object': None, 'service_tier': None, 'system_fingerprint': None, 'usage': ('openai.CompletionUsage', 'one')},
    'openai.ChatCompletionMessage': {'content': None, 'refusal': None, 'role': None, 'annotations': ('openai.Annotation', 'list'), 'audio': ('openai.ChatCompletionAudio', 'one'), 'function_call': ('openai.FunctionCall', 'one'), 'tool_calls': ('union:openai.ChatCompletionMessage.tool_calls', 'list')},
    'openai.ChatCompletionMessageCustomToolCall': {'id': None, 'custom': ('openai.Custom', 'one'), 'type': None},
    'openai.ChatCompletionMessageFunctionToolCall': {'id': None, 'function': ('openai.Function', 'one'), 'type': None},
    'openai.ChatCompletionTokenLogprob': {'token': None, 'bytes': None, 'logprob': None, 'top_logprobs': ('openai.TopLogprob', 'list')},
    'openai.Choice': {'finish_reason': None, 'index': None, 'logprobs': ('openai.ChoiceLogprobs', 'one'), 'message': ('openai.ChatCompletionMessage', 'one')},
    'openai.Choice@chat_completion_chunk': {'delta': ('openai.ChoiceDelta', 'one'), 'finish_reason': None, 'index': None, 'logprobs': ('openai.ChoiceLogprobs@chat_completion_chunk', 'one')},
    'openai.ChoiceDelta': {'content': None, 'function_call': ('openai.ChoiceDeltaFunctionCall', 'one'), 'refusal': None, 'role': None, 'tool_calls': ('openai.ChoiceDeltaToolCall', 'list')},
    'openai.ChoiceDeltaFunctionCall': {'arguments': None, 'name': None},
    'openai.ChoiceDeltaToolCall': {'index': None, 'id': None, 'function': ('openai.ChoiceDeltaToolCallFunction', 'one'), 'type': None},
    'openai.ChoiceDeltaToolCallFunction': {'arguments': None, 'name': None},
    'openai.ChoiceLogprobs': {'content': ('openai.ChatCompletionTokenLogprob', 'list'), 'refusal': ('openai.ChatCompletionTokenLogprob', 'list')},
    'openai.ChoiceLogprobs@chat_completion_chunk': {'content': ('openai.ChatCompletionTokenLogprob', 'list'), 'refusal': ('openai.ChatCompletionTokenLogprob', 'list')},
    'openai.CodeInterpreter': {'container': None, 'type': None},
    'openai.ComparisonFilter': {'key': None, 'type': None, 'value': None},
    'openai.CompletionTokensDetails': {'accepted_prediction_tokens': None, 'audio_tokens': None, 'reasoning_tokens': None, 'rejected_prediction_tokens': None},
    'openai.CompletionUsage': {'completion_tokens': None, 'prompt_tokens': None, 'total_tokens': None, 'completion_tokens_details': ('openai.CompletionTokensDetails', 'one'), 'prompt_tokens_details': ('openai.PromptTokensDetails', 'one')},
    'openai.CompoundFilter': {'filters': None, 'type': None},
    'openai.ComputerTool': {'display_height': None, 'display_width': None, 'environment': None, 'type': None},
    'openai.ContainerAuto': {'type': None, 'file_ids': None, 'memory_limit': None, 'network_policy': ('union:openai.ContainerAuto.network_policy', 'one'), 'skills': ('union:openai.ContainerAuto.skills', 'list')},
    'openai.ContainerNetworkPolicyAllowlist': {'allowed_domains': None, 'type': None, 'domain_secrets': ('openai.ContainerNetworkPolicyDomainSecret', 'list')},
    'openai.ContainerNetworkPolicyDisabled': {'type': None},
    'openai.ContainerNetworkPolicyDomainSecret': {'domain': None, 'name': None, 'value': None},
    'openai.ContainerReference': {'container_id': None, 'type': None},
    'openai.Content': {'text': None, 'type': None},
    'openai.Conversation': {'id': None},
    'openai.Custom': {'input': None, 'name': None},
    'openai.CustomTool': {'name': None, 'type': None, 'description': None, 'format': ('union:openai.CustomTool.format', 'one')},
    'openai.FileSearchTool': {'type': None, 'vector_store_ids': None, 'filters': ('union:openai.FileSearchTool.filters', 'one'), 'max_num_results': None, 'ranking_options': ('openai.RankingOptions', 'one')},
    'openai.Filters': {'allowed_domains': None},
    'openai.Function': {'arguments': None, 'name': None},
    'openai.FunctionCall': {'arguments': None, 'name': None},
    'openai.FunctionShellTool': {'type': None, 'environment': ('union:openai.FunctionShellTool.environment', 'one')},
    'openai.FunctionTool': {'name': None, 'parameters': None, 'strict': None, 'type': None, 'description': None},
    'openai.Grammar': {'definition': None, 'syntax': None, 'type': None},
    'openai.ImageGeneration': {'type': None, 'action': None, 'background': None, 'input_fidelity': None, 'input_image_mask': ('openai.ImageGenerationInputImageMask', 'one'), 'model': None, 'moderation': None, 'output_compression': None, 'output_format': None, 'partial_images': None, 'quality': None, 'size': None},
    'openai.ImageGenerationCall': {'id': None, 'result': None, 'status': None, 'type': None},
    'openai.ImageGenerationInputImageMask': {'file_id': None, 'image_url': None},
    'openai.IncompleteDetails': {'reason': None},
    'openai.InlineSkill': {'description': None, 'name': None, 'source': ('openai.InlineSkillSource', 'one'), 'type': None},
    'openai.InlineSkillSource': {'data': None, 'media_type': None, 'type': None},
    'openai.InputTokensDetails': {'cached_tokens': None},
    'openai.LocalEnvironment': {'type': None, 'skills': ('openai.LocalSkill', 'list')},
    'openai.LocalShell': {'type': None},
    'openai.LocalShellCall': {'id': None, 'action': ('openai.LocalShellCallAction', 'one'), 'call_id': None, 'status': None, 'type': None},
    'openai.LocalShellCallAction': {'command': None, 'env': None, 'type': None, 'timeout_ms': None, 'user': None, 'working_directory': None},
    'openai.LocalSkill': {'description': None, 'name': None, 'path': None},
    'openai.Logprob': {'token': None, 'bytes': None, 'logprob': None, 'top_logprobs': ('openai.LogprobTopLogprob', 'list')},
    'openai.Logprob@response_text_delta_event': {'token': None, 'logprob': None, 'top_logprobs': ('openai.LogprobTopLogprob@response_text_delta_event', 'list')},
    'openai.Logprob@response_text_done_event': {'token': None, 'logprob': None, 'top_logprobs': ('openai.LogprobTopLogprob@response_text_done_event', 'list')},
    'openai.LogprobTopLogprob': {'token': None, 'bytes': None, 'logprob': None},
    'openai.LogprobTopLogprob@response_text_delta_event': {'token': None, 'logprob': None},
    'openai.LogprobTopLogprob@response_text_done_event': {'token': None, 'logprob': None},
    'openai.Mcp': {'server_label': None, 'type': None, 'allowed_tools': None, 'authorization': None, 'connector_id': None, 'headers': None, 'require_approval': None, 'server_description': None, 'server_url': None},
    'openai.McpApprovalRequest': {'id': None, 'arguments': None, 'name': None, 'server_label': None, 'type': None},
    'openai.McpCall': {'id': None, 'arguments': None, 'name': None, 'server_label': None, 'type': None, 'approval_request_id': None, 'error': None, 'output': None, 'status': None},
    'openai.McpListTools': {'id': None, 'server_label': None, 'tools': ('openai.McpListToolsTool', 'list'), 'type': None, 'error': None},
    'openai.McpListToolsTool': {'input_schema': None, 'name': None, 'annotations': None, 'description': None},
    'openai.OperationCreateFile': {'diff': None, 'path': None, 'type': None},
    'openai.OperationDeleteFile': {'path': None, 'type': None},
    'openai.OperationUpdateFile': {'diff': None, 'path': None, 'type': None},
    'openai.Output': {'outcome': ('union:openai.Output.outcome', 'one'), 'stderr': None, 'stdout': None, 'created_by': None},
    'openai.OutputImage': {'type': None, 'url': None},
    'openai.OutputLogs': {'logs': None, 'type': None},
    'openai.OutputOutcomeExit': {'exit_code': None, 'type': None},
    'openai.OutputOutcomeTimeout': {'type': None},
    'openai.OutputTokensDetails': {'reasoning_tokens': None},
    'openai.Part': {'text': None, 'type': None},
    'openai.Part@response_reasoning_summary_part_done_event': {'text': None, 'type': None},
    'openai.PartReasoningText': {'text': None, 'type': None},
    'openai.PartReasoningText@response_content_part_done_event': {'text': None, 'type': None},
    'openai.PendingSafetyCheck': {'id': None, 'code': None, 'message': None},
    'openai.PromptTokensDetails': {'audio_tokens': None, 'cached_tokens': None},
    'openai.RankingOptions': {'hybrid_search': ('openai.RankingOptionsHybridSearch', 'one'), 'ranker': None, 'score_threshold': None},
    'openai.RankingOptionsHybridSearch': {'embedding_weight': None, 'text_weight': None},
    'openai.Reasoning': {'effort': None, 'generate_summary': None, 'summary': None},
    'openai.Response': {'id': None, 'created_at': None, 'error': ('openai.ResponseError', 'one'), 'incomplete_details': ('openai.IncompleteDetails', 'one'), 'instructions': None, 'metadata': None, 'model': None, 'object': None, 'output': ('union:openai.Response.output', 'list'), 'parallel_tool_calls': None, 'temperature': None, 'tool_choice': None, 'tools': ('union:openai.Response.tools', 'list'), 'top_p': None, 'background': None, 'completed_at': None, 'conversation': ('openai.Conversation', 'one'), 'max_output_tokens': None, 'max_tool_calls': None, 'previous_response_id': None, 'prompt': ('openai.ResponsePrompt', 'one'), 'prompt_cache_key': None, 'prompt_cache_retention': None, 'reasoning': ('openai.Reasoning', 'one'), 'safety_identifier': None, 'service_tier': None, 'status': None, 'text': ('openai.ResponseTextConfig', 'one'), 'top_logprobs': None, 'truncation': None, 'usage': ('openai.ResponseUsage', 'one'), 'user': None},
    'openai.ResponseApplyPatchToolCall': {'id': None, 'call_id': None, 'operation': ('union:openai.ResponseApplyPatchToolCall.operation', 'one'), 'status': None, 'type': None, 'created_by': None},
    'openai.ResponseApplyPatchToolCallOutput': {'id': None, 'call_id': None, 'status': None, 'type': None, 'created_by': None, 'output': None},
    'openai.ResponseAudioDeltaEvent': {'delta': None, 'sequence_number': None, 'type': None},
    'openai.ResponseAudioDoneEvent': {'sequence_number': None, 'type': None},
    'openai.ResponseAudioTranscriptDeltaEvent': {'delta': None, 'sequence_number': None, 'type': None},
    'openai.ResponseAudioTranscriptDoneEvent': {'sequence_number': None, 'type': None},
    'openai.ResponseCodeInterpreterCallCodeDeltaEvent': {'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseCodeInterpreterCallCodeDoneEvent': {'code': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseCodeInterpreterCallCompletedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseCodeInterpreterCallInProgressEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseCodeInterpreterCallInterpretingEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseCodeInterpreterToolCall': {'id': None, 'code': None, 'container_id': None, 'outputs': ('union:openai.ResponseCodeInterpreterToolCall.outputs', 'list'), 'status': None, 'type': None},
    'openai.ResponseCompactionItem': {'id': None, 'encrypted_content': None, 'type': None, 'created_by': None},
    'openai.ResponseCompletedEvent': {'response': ('openai.Response', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseComputerToolCall': {'id': None, 'action': ('union:openai.ResponseComputerToolCall.action', 'one'), 'call_id': None, 'pending_safety_checks': ('openai.PendingSafetyCheck', 'list'), 'status': None, 'type': None},
    'openai.ResponseContainerReference': {'container_id': None, 'type': None},
    'openai.ResponseContentPartAddedEvent': {'content_index': None, 'item_id': None, 'output_index': None, 'part': ('union:openai.ResponseContentPartAddedEvent.part', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseContentPartDoneEvent': {'content_index': None, 'item_id': None, 'output_index': None, 'part': ('union:openai.ResponseContentPartDoneEvent.part', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseCreatedEvent': {'response': ('openai.Response', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseCustomToolCall': {'call_id': None, 'input': None, 'name': None, 'type': None, 'id': None},
    'openai.ResponseCustomToolCallInputDeltaEvent': {'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseCustomToolCallInputDoneEvent': {'input': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseError': {'code': None, 'message': None},
    'openai.ResponseErrorEvent': {'code': None, 'message': None, 'param': None, 'sequence_number': None, 'type': None},
    'openai.ResponseFailedEvent': {'response': ('openai.Response', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseFileSearchCallCompletedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseFileSearchCallInProgressEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseFileSearchCallSearchingEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseFileSearchToolCall': {'id': None, 'queries': None, 'status': None, 'type': None, 'results': ('openai.Result', 'list')},
    'openai.ResponseFormatJSONObject': {'type': None},
    'openai.ResponseFormatText': {'type': None},
    'openai.ResponseFormatTextJSONSchemaConfig': {'name': None, 'schema': None, 'type': None, 'description': None, 'strict': None},
    'openai.ResponseFunctionCallArgumentsDeltaEvent': {'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseFunctionCallArgumentsDoneEvent': {'arguments': None, 'item_id': None, 'name': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseFunctionShellToolCall': {'id': None, 'action': ('openai.Action', 'one'), 'call_id': None, 'environment': ('union:openai.ResponseFunctionShellToolCall.environment', 'one'), 'status': None, 'type': None, 'created_by': None},
    'openai.ResponseFunctionShellToolCallOutput': {'id': None, 'call_id': None, 'max_output_length': None, 'output': ('openai.Output', 'list'), 'status': None, 'type': None, 'created_by': None},
    'openai.ResponseFunctionToolCall': {'arguments': None, 'call_id': None, 'name': None, 'type': None, 'id': None, 'status': None},
    'openai.ResponseFunctionWebSearch': {'id': None, 'action': ('union:openai.ResponseFunctionWebSearch.action', 'one'), 'status': None, 'type': None},
    'openai.ResponseImageGenCallCompletedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseImageGenCallGeneratingEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseImageGenCallInProgressEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseImageGenCallPartialImageEvent': {'item_id': None, 'output_index': None, 'partial_image_b64': None, 'partial_image_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseInProgressEvent': {'response': ('openai.Response', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseIncompleteEvent': {'response': ('openai.Response', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseLocalEnvironment': {'type': None},
    'openai.ResponseMcpCallArgumentsDeltaEvent': {'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpCallArgumentsDoneEvent': {'arguments': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpCallCompletedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpCallFailedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpCallInProgressEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpListToolsCompletedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpListToolsFailedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseMcpListToolsInProgressEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseOutputItemAddedEvent': {'item': ('union:openai.Response.output', 'one'), 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseOutputItemDoneEvent': {'item': ('union:openai.Response.output', 'one'), 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseOutputMessage': {'id': None, 'content': ('union:openai.ResponseOutputMessage.content', 'list'), 'role': None, 'status': None, 'type': None, 'phase': None},
    'openai.ResponseOutputRefusal': {'refusal': None, 'type': None},
    'openai.ResponseOutputText': {'annotations': ('union:openai.ResponseOutputText.annotations', 'list'), 'text': None, 'type': None, 'logprobs': ('openai.Logprob', 'list')},
    'openai.ResponseOutputTextAnnotationAddedEvent': {'annotation': None, 'annotation_index': None, 'content_index': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponsePrompt': {'id': None, 'variables': None, 'version': None},
    'openai.ResponseQueuedEvent': {'response': ('openai.Response', 'one'), 'sequence_number': None, 'type': None},
    'openai.ResponseReasoningItem': {'id': None, 'summary': ('openai.Summary', 'list'), 'type': None, 'content': ('openai.Content', 'list'), 'encrypted_content': None, 'status': None},
    'openai.ResponseReasoningSummaryPartAddedEvent': {'item_id': None, 'output_index': None, 'part': ('openai.Part', 'one'), 'sequence_number': None, 'summary_index': None, 'type': None},
    'openai.ResponseReasoningSummaryPartDoneEvent': {'item_id': None, 'output_index': None, 'part': ('openai.Part@response_reasoning_summary_part_done_event', 'one'), 'sequence_number': None, 'summary_index': None, 'type': None},
    'openai.ResponseReasoningSummaryTextDeltaEvent': {'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'summary_index': None, 'type': None},
    'openai.ResponseReasoningSummaryTextDoneEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'summary_index': None, 'text': None, 'type': None},
    'openai.ResponseReasoningTextDeltaEvent': {'content_index': None, 'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseReasoningTextDoneEvent': {'content_index': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'text': None, 'type': None},
    'openai.ResponseRefusalDeltaEvent': {'content_index': None, 'delta': None, 'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseRefusalDoneEvent': {'content_index': None, 'item_id': None, 'output_index': None, 'refusal': None, 'sequence_number': None, 'type': None},
    'openai.ResponseTextConfig': {'format': ('union:openai.ResponseTextConfig.format', 'one'), 'verbosity': None},
    'openai.ResponseTextDeltaEvent': {'content_index': None, 'delta': None, 'item_id': None, 'logprobs': ('openai.Logprob@response_text_delta_event', 'list'), 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseTextDoneEvent': {'content_index': None, 'item_id': None, 'logprobs': ('openai.Logprob@response_text_done_event', 'list'), 'output_index': None, 'sequence_number': None, 'text': None, 'type': None},
    'openai.ResponseUsage': {'input_tokens': None, 'input_tokens_details': ('openai.InputTokensDetails', 'one'), 'output_tokens': None, 'output_tokens_details': ('openai.OutputTokensDetails', 'one'), 'total_tokens': None},
    'openai.ResponseWebSearchCallCompletedEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseWebSearchCallInProgressEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.ResponseWebSearchCallSearchingEvent': {'item_id': None, 'output_index': None, 'sequence_number': None, 'type': None},
    'openai.Result': {'attributes': None, 'file_id': None, 'filename': None, 'score': None, 'text': None},
    'openai.SkillReference': {'skill_id': None, 'type': None, 'version': None},
    'openai.Summary': {'text': None, 'type': None},
    'openai.Text': {'type': None},
    'openai.TopLogprob': {'token': None, 'bytes': None, 'logprob': None},
    'openai.UserLocation': {'city': None, 'country': None, 'region': None, 'timezone': None, 'type': None},
    'openai.UserLocation@web_search_preview_tool': {'type': None, 'city': None, 'country': None, 'region': None, 'timezone': None},
    'openai.WebSearchPreviewTool': {'type': None, 'search_context_size': None, 'user_location': ('openai.UserLocation@web_search_preview_tool', 'one')},
    'openai.WebSearchTool': {'type': None, 'filters': ('openai.Filters', 'one'), 'search_context_size': None, 'user_location': ('openai.UserLocation', 'one')},
}

UNIONS = {
    'anthropic.BashCodeExecutionToolResultBlock.content': {'bash_code_execution_tool_result_error': 'anthropic.BashCodeExecutionToolResultError', 'bash_code_execution_result': 'anthropic.BashCodeExecutionResultBlock'},
    'anthropic.CodeExecutionToolResultBlock.content': {'code_execution_tool_result_error': 'anthropic.CodeExecutionToolResultError', 'code_execution_result': 'anthropic.CodeExecutionResultBlock', 'encrypted_code_execution_result': 'anthropic.EncryptedCodeExecutionResultBlock'},
    'anthropic.DocumentBlock.source': {'base64': 'anthropic.Base64PDFSource', 'text': 'anthropic.PlainTextSource'},
    'anthropic.Message.content': {'text': 'anthropic.TextBlock', 'thinking': 'anthropic.ThinkingBlock', 'redacted_thinking': 'anthropic.RedactedThinkingBlock', 'tool_use': 'anthropic.ToolUseBlock', 'server_tool_use': 'anthropic.ServerToolUseBlock', 'web_search_tool_result': 'anthropic.WebSearchToolResultBlock', 'web_fetch_tool_result': 'anthropic.WebFetchToolResultBlock', 'code_execution_tool_result': 'anthropic.CodeExecutionToolResultBlock', 'bash_code_execution_tool_result': 'anthropic.BashCodeExecutionToolResultBlock', 'text_editor_code_execution_tool_result': 'anthropic.TextEditorCodeExecutionToolResultBlock', 'tool_search_tool_result': 'anthropic.ToolSearchToolResultBlock', 'container_upload': 'anthropic.ContainerUploadBlock'},
    'anthropic.ParsedMessage.content': {'text': 'anthropic.ParsedTextBlock', 'thinking': 'anthropic.ThinkingBlock', 'redacted_thinking': 'anthropic.RedactedThinkingBlock', 'tool_use': 'anthropic.ToolUseBlock', 'server_tool_use': 'anthropic.ServerToolUseBlock', 'web_search_tool_result': 'anthropic.WebSearchToolResultBlock'},
    'anthropic.ParsedMessage_TypeVar.content': {'text': 'anthropic.ParsedTextBlock_TypeVar', 'thinking': 'anthropic.ThinkingBlock', 'redacted_thinking': 'anthropic.RedactedThinkingBlock', 'tool_use': 'anthropic.ToolUseBlock', 'server_tool_use': 'anthropic.ServerToolUseBlock', 'web_search_tool_result': 'anthropic.WebSearchToolResultBlock'},
    'anthropic.RawContentBlockDeltaEvent.delta': {'text_delta': 'anthropic.TextDelta', 'input_json_delta': 'anthropic.InputJSONDelta', 'citations_delta': 'anthropic.CitationsDelta', 'thinking_delta': 'anthropic.ThinkingDelta', 'signature_delta': 'anthropic.SignatureDelta'},
    'anthropic.TextBlock.citations': {'char_location': 'anthropic.CitationCharLocation', 'page_location': 'anthropic.CitationPageLocation', 'content_block_location': 'anthropic.CitationContentBlockLocation', 'web_search_result_location': 'anthropic.CitationsWebSearchResultLocation', 'search_result_location': 'anthropic.CitationsSearchResultLocation'},
    'anthropic.TextEditorCodeExecutionToolResultBlock.content': {'text_editor_code_execution_tool_result_error': 'anthropic.TextEditorCodeExecutionToolResultError', 'text_editor_code_execution_view_result': 'anthropic.TextEditorCodeExecutionViewResultBlock', 'text_editor_code_execution_create_result': 'anthropic.TextEditorCodeExecutionCreateResultBlock', 'text_editor_code_execution_str_replace_result': 'anthropic.TextEditorCodeExecutionStrReplaceResultBlock'},
    'anthropic.ToolSearchToolResultBlock.content': {'tool_search_tool_result_error': 'anthropic.ToolSearchToolResultError', 'tool_search_tool_search_result': 'anthropic.ToolSearchToolSearchResultBlock'},
    'anthropic.ToolUseBlock.caller': {'direct': 'anthropic.DirectCaller', 'code_execution_20250825': 'anthropic.ServerToolCaller', 'code_execution_20260120': 'anthropic.ServerToolCaller20260120'},
    'anthropic.WebFetchToolResultBlock.content': {'web_fetch_tool_result_error': 'anthropic.WebFetchToolResultErrorBlock', 'web_fetch_result': 'anthropic.WebFetchBlock'},
    'anthropic.raw_event': {'message_start': 'anthropic.RawMessageStartEvent', 'message_delta': 'anthropic.RawMessageDeltaEvent', 'message_stop': 'anthropic.RawMessageStopEvent', 'content_block_start': 'anthropic.RawContentBlockStartEvent', 'content_block_delta': 'anthropic.RawContentBlockDeltaEvent', 'content_block_stop': 'anthropic.RawContentBlockStopEvent'},
    'anthropic.stream_event': {'text': 'anthropic.TextEvent', 'citation': 'anthropic.CitationEvent', 'thinking': 'anthropic.ThinkingEvent', 'signature': 'anthropic.SignatureEvent', 'input_json': 'anthropic.InputJsonEvent', 'message_start': 'anthropic.RawMessageStartEvent', 'message_delta': 'anthropic.RawMessageDeltaEvent', 'message_stop': 'anthropic.ParsedMessageStopEvent', 'content_block_start': 'anthropic.RawContentBlockStartEvent', 'content_block_delta': 'anthropic.RawContentBlockDeltaEvent', 'content_block_stop': 'anthropic.ParsedContentBlockStopEvent'},
    'openai.ChatCompletionMessage.tool_calls': {'function': 'openai.ChatCompletionMessageFunctionToolCall', 'custom': 'openai.ChatCompletionMessageCustomToolCall'},
    'openai.ContainerAuto.network_policy': {'disabled': 'openai.ContainerNetworkPolicyDisabled', 'allowlist': 'openai.ContainerNetworkPolicyAllowlist'},
    'openai.ContainerAuto.skills': {'skill_reference': 'openai.SkillReference', 'inline': 'openai.InlineSkill'},
    'openai.CustomTool.format': {'text': 'openai.Text', 'grammar': 'openai.Grammar'},
    'openai.FileSearchTool.filters': {'eq': 'openai.ComparisonFilter', 'ne': 'openai.ComparisonFilter', 'gt': 'openai.ComparisonFilter', 'gte': 'openai.ComparisonFilter', 'lt': 'openai.ComparisonFilter', 'lte': 'openai.ComparisonFilter', 'and': 'openai.CompoundFilter', 'or': 'openai.CompoundFilter'},
    'openai.FunctionShellTool.environment': {'container_auto': 'openai.ContainerAuto', 'local': 'openai.LocalEnvironment', 'container_reference': 'openai.ContainerReference'},
    'openai.Output.outcome': {'timeout': 'openai.OutputOutcomeTimeout', 'exit': 'openai.OutputOutcomeExit'},
    'openai.Response.output': {'message': 'openai.ResponseOutputMessage', 'file_search_call': 'openai.ResponseFileSearchToolCall', 'function_call': 'openai.ResponseFunctionToolCall', 'web_search_call': 'openai.ResponseFunctionWebSearch', 'computer_call': 'openai.ResponseComputerToolCall', 'reasoning': 'openai.ResponseReasoningItem', 'compaction': 'openai.ResponseCompactionItem', 'image_generation_call': 'openai.ImageGenerationCall', 'code_interpreter_call': 'openai.ResponseCodeInterpreterToolCall', 'local_shell_call': 'openai.LocalShellCall', 'shell_call': 'openai.ResponseFunctionShellToolCall', 'shell_call_output': 'openai.ResponseFunctionShellToolCallOutput', 'apply_patch_call': 'openai.ResponseApplyPatchToolCall', 'apply_patch_call_output': 'openai.ResponseApplyPatchToolCallOutput', 'mcp_call': 'openai.McpCall', 'mcp_list_tools': 'openai.McpListTools', 'mcp_approval_request': 'openai.McpApprovalRequest', 'custom_tool_call': 'openai.ResponseCustomToolCall'},
    'openai.Response.tools': {'function': 'openai.FunctionTool', 'file_search': 'openai.FileSearchTool', 'computer_use_preview': 'openai.ComputerTool', 'web_search': 'openai.WebSearchTool', 'web_search_2025_08_26': 'openai.WebSearchTool', 'mcp': 'openai.Mcp', 'code_interpreter': 'openai.CodeInterpreter', 'image_generation': 'openai.ImageGeneration', 'local_shell': 'openai.LocalShell', 'shell': 'openai.FunctionShellTool', 'custom': 'openai.CustomTool', 'web_search_preview': 'openai.WebSearchPreviewTool', 'web_search_preview_2025_03_11': 'openai.WebSearchPreviewTool', 'apply_patch': 'openai.ApplyPatchTool'},
    'openai.ResponseApplyPatchToolCall.operation': {'create_file': 'openai.OperationCreateFile', 'delete_file': 'openai.OperationDeleteFile', 'update_file': 'openai.OperationUpdateFile'},
    'openai.ResponseCodeInterpreterToolCall.outputs': {'logs': 'openai.OutputLogs', 'image': 'openai.OutputImage'},
    'openai.ResponseComputerToolCall.action': {'click': 'openai.ActionClick', 'double_click': 'openai.ActionDoubleClick', 'drag': 'openai.ActionDrag', 'keypress': 'openai.ActionKeypress', 'move': 'openai.ActionMove', 'screenshot': 'openai.ActionScreenshot', 'scroll': 'openai.ActionScroll', 'type': 'openai.ActionType', 'wait': 'openai.ActionWait'},
    'openai.ResponseContentPartAddedEvent.part': {'output_text': 'openai.ResponseOutputText', 'refusal': 'openai.ResponseOutputRefusal', 'reasoning_text': 'openai.PartReasoningText'},
    'openai.ResponseContentPartDoneEvent.part': {'output_text': 'openai.ResponseOutputText', 'refusal': 'openai.ResponseOutputRefusal', 'reasoning_text': 'openai.PartReasoningText@response_content_part_done_event'},
    'openai.ResponseFunctionShellToolCall.environment': {'local': 'openai.ResponseLocalEnvironment', 'container_reference': 'openai.ResponseContainerReference'},
    'openai.ResponseFunctionWebSearch.action': {'search': 'openai.ActionSearch', 'open_page': 'openai.ActionOpenPage', 'find_in_page': 'openai.ActionFind'},
    'openai.ResponseOutputMessage.content': {'output_text': 'openai.ResponseOutputText', 'refusal': 'openai.ResponseOutputRefusal'},
    'openai.ResponseOutputText.annotations': {'file_citation': 'openai.AnnotationFileCitation', 'url_citation': 'openai.AnnotationURLCitation@response_output_text', 'container_file_citation': 'openai.AnnotationContainerFileCitation', 'file_path': 'openai.AnnotationFilePath'},
    'openai.ResponseTextConfig.format': {'text': 'openai.ResponseFormatText', 'json_schema': 'openai.ResponseFormatTextJSONSchemaConfig', 'json_object': 'openai.ResponseFormatJSONObject'},
    'responses.event': {'response.audio.delta': 'openai.ResponseAudioDeltaEvent', 'response.audio.done': 'openai.ResponseAudioDoneEvent', 'response.audio.transcript.delta': 'openai.ResponseAudioTranscriptDeltaEvent', 'response.audio.transcript.done': 'openai.ResponseAudioTranscriptDoneEvent', 'response.code_interpreter_call_code.delta': 'openai.ResponseCodeInterpreterCallCodeDeltaEvent', 'response.code_interpreter_call_code.done': 'openai.ResponseCodeInterpreterCallCodeDoneEvent', 'response.code_interpreter_call.completed': 'openai.ResponseCodeInterpreterCallCompletedEvent', 'response.code_interpreter_call.in_progress': 'openai.ResponseCodeInterpreterCallInProgressEvent', 'response.code_interpreter_call.interpreting': 'openai.ResponseCodeInterpreterCallInterpretingEvent', 'response.completed': 'openai.ResponseCompletedEvent', 'response.content_part.added': 'openai.ResponseContentPartAddedEvent', 'response.content_part.done': 'openai.ResponseContentPartDoneEvent', 'response.created': 'openai.ResponseCreatedEvent', 'error': 'openai.ResponseErrorEvent', 'response.file_search_call.completed': 'openai.ResponseFileSearchCallCompletedEvent', 'response.file_search_call.in_progress': 'openai.ResponseFileSearchCallInProgressEvent', 'response.file_search_call.searching': 'openai.ResponseFileSearchCallSearchingEvent', 'response.function_call_arguments.delta': 'openai.ResponseFunctionCallArgumentsDeltaEvent', 'response.function_call_arguments.done': 'openai.ResponseFunctionCallArgumentsDoneEvent', 'response.in_progress': 'openai.ResponseInProgressEvent', 'response.failed': 'openai.ResponseFailedEvent', 'response.incomplete': 'openai.ResponseIncompleteEvent', 'response.output_item.added': 'openai.ResponseOutputItemAddedEvent', 'response.output_item.done': 'openai.ResponseOutputItemDoneEvent', 'response.reasoning_summary_part.added': 'openai.ResponseReasoningSummaryPartAddedEvent', 'response.reasoning_summary_part.done': 'openai.ResponseReasoningSummaryPartDoneEvent', 'response.reasoning_summary_text.delta': 'openai.ResponseReasoningSummaryTextDeltaEvent', 'response.reasoning_summary_text.done': 'openai.ResponseReasoningSummaryTextDoneEvent', 'response.reasoning_text.delta': 'openai.ResponseReasoningTextDeltaEvent', 'response.reasoning_text.done': 'openai.ResponseReasoningTextDoneEvent', 'response.refusal.delta': 'openai.ResponseRefusalDeltaEvent', 'response.refusal.done': 'openai.ResponseRefusalDoneEvent', 'response.output_text.delta': 'openai.ResponseTextDeltaEvent', 'response.output_text.done': 'openai.ResponseTextDoneEvent', 'response.web_search_call.completed': 'openai.ResponseWebSearchCallCompletedEvent', 'response.web_search_call.in_progress': 'openai.ResponseWebSearchCallInProgressEvent', 'response.web_search_call.searching': 'openai.ResponseWebSearchCallSearchingEvent', 'response.image_generation_call.completed': 'openai.ResponseImageGenCallCompletedEvent', 'response.image_generation_call.generating': 'openai.ResponseImageGenCallGeneratingEvent', 'response.image_generation_call.in_progress': 'openai.ResponseImageGenCallInProgressEvent', 'response.image_generation_call.partial_image': 'openai.ResponseImageGenCallPartialImageEvent', 'response.mcp_call_arguments.delta': 'openai.ResponseMcpCallArgumentsDeltaEvent', 'response.mcp_call_arguments.done': 'openai.ResponseMcpCallArgumentsDoneEvent', 'response.mcp_call.completed': 'openai.ResponseMcpCallCompletedEvent', 'response.mcp_call.failed': 'openai.ResponseMcpCallFailedEvent', 'response.mcp_call.in_progress': 'openai.ResponseMcpCallInProgressEvent', 'response.mcp_list_tools.completed': 'openai.ResponseMcpListToolsCompletedEvent', 'response.mcp_list_tools.failed': 'openai.ResponseMcpListToolsFailedEvent', 'response.mcp_list_tools.in_progress': 'openai.ResponseMcpListToolsInProgressEvent', 'response.output_text.annotation.added': 'openai.ResponseOutputTextAnnotationAddedEvent', 'response.queued': 'openai.ResponseQueuedEvent', 'response.custom_tool_call_input.delta': 'openai.ResponseCustomToolCallInputDeltaEvent', 'response.custom_tool_call_input.done': 'openai.ResponseCustomToolCallInputDoneEvent'},
}

ALIASES = {'openai.ResponseFormatTextJSONSchemaConfig': {'schema': 'schema_'}}
# fmt: on
