"""Rows (win32 only): upstream's OWN Windows reds at release tag v0.21.6 -- retired by an upstream fix.

Every id here was red on the pure tag ``v0.21.6`` (``818c13be1d``, a detached worktree, no
fork code) AND on the fork's main in the 2026-10-10 release-merge landing gate. A per-test
strict xfail, not a skip-list row: the rest of each file keeps running, and an upstream fix
turns the row into an XPASS(strict) red that retires it. The next release merge re-runs
this table on its tag and drops every XPASS (fork-hygiene class row, 2026-10-10).

One ``ROWS`` table, already host-filtered; ``hooks._merge`` concatenates the tables.
The map is ``tests/_downstream/id_markers/__init__.py``.
"""

from __future__ import annotations

import pytest

from tests._downstream.id_markers.reasons import _up_red, _WIN

__layer__ = "models"

_REASON = "red on pure upstream tag v0.21.6 818c13be1d on Windows (2026-10-10 release merge)"

_NODES = (
        'tests/agent/lsp/test_client_e2e.py::test_reader_failure_retires_client_and_rejects_later_work[clean_eof]',
        'tests/agent/lsp/test_service.py::test_service_replaces_client_after_reader_failure[clean_eof]',
        'tests/agent/test_aux_progress_streaming.py::TestAggregateChatStream::test_silent_stream_fails_fast_through_the_real_transport[primary]',
        'tests/agent/test_aux_progress_streaming.py::TestAggregateChatStream::test_silent_stream_fails_fast_through_the_real_transport[recovery_rung]',
        'tests/agent/test_context_references.py::test_blocks_canonical_read_denylist_credential_stores',
        'tests/agent/test_dead_connection_cleanup.py::test_cleanup_rebuilds_dead_primary_client',
        'tests/agent/test_dead_connection_cleanup.py::test_cleanup_retires_dead_cached_request_client',
        'tests/agent/test_subdirectory_hints.py::TestHomeWorkingDirGuard::test_home_cwd_never_injects_subtree_hints',
        'tests/agent/test_subdirectory_hints.py::TestHomeWorkingDirGuard::test_home_guard_blocks_direct_load_path',
        'tests/agent/test_subdirectory_hints.py::TestHomeWorkingDirGuard::test_session_workspace_adoption_rebinds_discovery',
        'tests/ci/test_desktop_release_tag_admission.py::test_downloadable_native_builds_refuse_to_ship_unsigned',
        'tests/ci/test_stable_release_graph.py::test_docker_recovery_refuses_to_replace_a_divergent_version_tag',
        'tests/ci/test_tag_builds_summary.py::test_admitted_failure_publishes_tag_info_without_promoting_channel[True]',
        'tests/computer_use/test_doctor.py::TestDriverCmdResolution::test_env_var_used_when_no_arg_given',
        'tests/computer_use/test_doctor.py::TestDriverCmdResolution::test_explicit_driver_cmd_arg_wins',
        'tests/conformance/persistence/test_cell5_delivery_outbox_exactly_once.py::test_boot_killed_inside_plain_redelivery_never_double_delivers',
        'tests/conformance/persistence/test_cell5_delivery_outbox_exactly_once.py::test_concurrent_reboots_claim_each_obligation_once',
        'tests/conformance/persistence/test_cell5_delivery_outbox_exactly_once.py::test_crash_between_send_and_record_never_double_delivers[attempting-unsent]',
        'tests/conformance/persistence/test_cell5_delivery_outbox_exactly_once.py::test_crash_between_send_and_record_never_double_delivers[recorded-unsent]',
        'tests/conformance/persistence/test_cell5_delivery_outbox_exactly_once.py::test_crash_between_send_and_record_never_double_delivers[resend-crash-attempting]',
        'tests/conformance/persistence/test_cell5_delivery_outbox_exactly_once.py::test_crash_between_send_and_record_never_double_delivers[sent-unacked]',
        'tests/cron/test_cron_bot_chat_delivery.py::test_turn_report_books_the_delivery_while_the_child_still_lingers',
        'tests/cron/test_cron_no_agent.py::test_run_job_no_agent_uses_configured_interpreter',
        'tests/cron/test_external_worker_config_hooks.py::test_worker_registers_owning_profile_config_hooks',
        'tests/cron/test_lifecycle_guard_heredoc_walk.py::test_mentioned_data_file_that_cannot_be_scanned_is_not_a_verdict',
        'tests/cron/test_lifecycle_guard_heredoc_walk.py::test_unquoted_heredoc_body_path_still_walked',
        'tests/cron/test_missed_window_catchup.py::TestMissedWindowCatchUp::test_fired_slot_is_not_replayed_after_restart',
        'tests/cron/test_missed_window_catchup.py::TestMissedWindowCatchUp::test_slot_lost_before_dispatch_fires_once_after_restart',
        'tests/cron/test_monitor_kind.py::test_monitor_script_uses_configured_interpreter',
        'tests/cron/test_restart_safe_worker.py::test_scoped_wrapper_exit_without_user_bus_names_the_cause_and_invalidates_probe',
        'tests/gateway/test_cgroup_cleanup.py::TestLiveGatewayGuard::test_reap_refuses_when_live_gateway_in_cgroup[restart]',
        'tests/gateway/test_cgroup_cleanup.py::TestLiveGatewayGuard::test_reap_refuses_when_live_gateway_in_cgroup[run]',
        'tests/gateway/test_complete_path_at_filter.py::test_remote_backend_completion_expands_tilde_on_the_backend',
        'tests/gateway/test_complete_path_at_filter.py::test_remote_backend_completion_lists_the_backend_not_the_host',
        'tests/gateway/test_complete_path_at_filter.py::test_remote_backend_completion_speaks_posix_from_a_windows_host',
        'tests/gateway/test_discord_attachment_receipts.py::test_media_uses_metadata_target_without_losing_direct_channel[send_multiple_images]',
        'tests/gateway/test_failure_writer_ownership.py::test_gateway_failure_writer_preserves_accepted_turn_identity',
        'tests/gateway/test_gateway_shutdown.py::test_pid_exists_zombie_via_psutil_returns_false',
        'tests/gateway/test_kanban_multiplex_served_profile_parity.py::test_worker_for_served_profile_gets_its_own_env_and_toolset_pin',
        'tests/gateway/test_multiplex_docker_media_delivery_scope.py::test_secondary_docker_media_resolves_via_its_own_mounts',
        'tests/gateway/test_native_warning_coverage.py::test_discord_rejected_media_preserves_caption_without_fake_receipt[False-False-send_multiple_images]',
        'tests/gateway/test_native_warning_coverage.py::test_discord_rejected_media_preserves_caption_without_fake_receipt[None-False-send_multiple_images]',
        'tests/gateway/test_process_cmdline_source.py::test_ps_still_answers_when_psutil_cannot',
        'tests/gateway/test_profile_serve_signature.py::test_profile_serve_signature_changes_on_replacement_with_pinned_mtime',
        'tests/gateway/test_readiness.py::test_collect_runtime_readiness_reports_healthy_local_runtime',
        'tests/gateway/test_reload_signal_logs_graceful_restart.py::test_sigusr1_handler_installed_by_start_gateway_logs_graceful_restart',
        'tests/gateway/test_remote_media_fetch.py::test_fetch_file_round_trips_bytes_and_enforces_the_in_sandbox_size_cap',
        'tests/gateway/test_status.py::TestReadProcessCmdlinePsFallback::test_ps_fallback_when_proc_unavailable',
        'tests/gateway/test_telegram_closewait_windows_live.py::test_drain_bounded_and_functional_when_close_wedges_live',
        'tests/gateway/test_telegram_closewait_windows_live.py::test_drain_recovers_after_server_half_close_live',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_chrome_debug_data_dir_created_owner_only',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_chrome_debug_data_dir_reconciles_legacy_world_readable',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_computer_use_cache_files_owner_only',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_gateway_media_cache_dirs_created_owner_only[get_audio_cache_dir]',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_gateway_media_cache_dirs_created_owner_only[get_document_cache_dir]',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_gateway_media_cache_dirs_created_owner_only[get_image_cache_dir]',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_gateway_media_cache_dirs_created_owner_only[get_screenshot_cache_dir]',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_gateway_media_cache_dirs_created_owner_only[get_video_cache_dir]',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_gateway_media_cache_files_owner_only',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_launch_stderr_log_owner_only',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_vision_media_cache_dirs_created_owner_only',
        'tests/hermes_cli/test_browser_connect_media_permissions.py::test_vision_media_cache_files_owner_only',
        'tests/hermes_cli/test_cli_import_without_patch_stdout.py::test_cli_imports_without_patch_stdout',
        'tests/hermes_cli/test_cli_import_without_patch_stdout.py::test_cli_patch_stdout_falls_back_to_nullcontext',
        'tests/hermes_cli/test_doctor_no_proxy_ipv6.py::test_run_probes_leaves_a_clean_environment_untouched',
        'tests/hermes_cli/test_goal_gates.py::test_gate_runs_in_the_session_workspace_not_the_backend_directory',
        'tests/hermes_cli/test_goal_gates.py::test_gate_without_a_session_workspace_keeps_the_launch_directory',
        'tests/hermes_cli/test_gui_command.py::test_gui_close_preview_flag_forwards_to_packaged_exe',
        'tests/hermes_cli/test_kanban_db.py::test_resolve_hermes_argv_prefers_module_form_over_path_shim',
        'tests/hermes_cli/test_linux_desktop_entry.py::test_install_keeps_foreign_files_at_the_legacy_path',
        'tests/hermes_cli/test_linux_desktop_entry.py::test_install_keeps_the_legacy_entry_as_a_hidden_alias',
        'tests/hermes_cli/test_linux_desktop_entry.py::test_install_opt_out_preserves_the_legacy_entry',
        'tests/hermes_cli/test_linux_desktop_entry.py::test_installed_entry_carries_the_window_app_id',
        'tests/hermes_cli/test_linux_desktop_entry.py::test_unchanged_entry_still_aliases_a_legacy_entry',
        'tests/hermes_cli/test_plugin_provider_picker_admission.py::test_external_process_plugin_authenticated_flag_tracks_binary_and_catalog_uses_fallback',
        'tests/hermes_cli/test_plugin_provider_picker_residue.py::test_any_external_process_plugin_counts_as_signed_in_when_its_binary_resolves',
        'tests/hermes_cli/test_plugin_provider_picker_residue.py::test_hermes_model_routes_registered_plugin_profiles_to_the_generic_flow',
        'tests/hermes_cli/test_relaunch.py::TestResolveHermesBin::test_prefers_absolute_argv0_when_executable',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[ordinary-None-False]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[ordinary-None-True]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[ordinary-reset-False]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[ordinary-reset-True]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[orphan-None-False]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[orphan-head-False]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[orphan-ref-False]',
        'tests/hermes_cli/test_update_autostash.py::test_update_preserves_local_work_and_rescues_orphan_before_reset[orphan-reset-False]',
        'tests/hermes_cli/test_update_host_obligation.py::test_an_unreadable_profile_roster_never_admits_a_private_restart_marker[profile]',
        'tests/hermes_cli/test_update_host_obligation.py::test_an_unreadable_profile_roster_never_admits_a_private_restart_marker[roster]',
        'tests/hermes_cli/test_update_interrupted_pull.py::test_an_empty_head_answer_keeps_the_marker',
        'tests/hermes_cli/test_update_interrupted_pull.py::test_restore_runs_the_installers_store_git_when_path_has_none',
        'tests/hermes_cli/test_update_pause_boundaries.py::test_consumption_checkpoints_debt_before_unlink_and_producer_death[False]',
        'tests/hermes_cli/test_update_pause_boundaries.py::test_consumption_checkpoints_debt_before_unlink_and_producer_death[True]',
        'tests/hermes_cli/test_update_pause_debt_windows_live.py::test_a_launch_recovering_an_unready_service_keeps_the_debt_without_stalling',
        'tests/hermes_cli/test_update_pause_debt_windows_live.py::test_a_running_service_owes_its_gateway_until_that_gateway_is_ready[absent]',
        'tests/hermes_cli/test_update_pause_debt_windows_live.py::test_a_running_service_owes_its_gateway_until_that_gateway_is_ready[ready]',
        'tests/hermes_cli/test_update_post_commit_followups.py::test_followup_line_is_the_one_both_desktop_handoffs_parse',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[fork-late-push-ok]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[fork-late]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[fork-upstream-push-ok]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[fork-upstream-reverted]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[fork-upstream-wrong-branch]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[fork-upstream]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[no-move]',
        'tests/hermes_cli/test_update_target_identity.py::test_branch_update_uses_real_refs_and_completion_request[wrong-branch]',
        'tests/hermes_cli/test_update_target_identity.py::test_stable_git_uses_remote_identity_without_moving_local_tags[fetch-refused]',
        'tests/hermes_cli/test_web_server_files.py::test_dangling_symlink_does_not_break_directory_listing',
        'tests/hermes_cli/test_worktree_gc.py::TestAuditVerdicts::test_clean_merged_tree_reaps',
        'tests/hermes_cli/test_worktree_gc.py::TestAuditVerdicts::test_patch_equivalent_commits_reap',
        'tests/hermes_cli/test_worktree_gc.py::TestAuditVerdicts::test_unique_commits_without_a_remote_keep_tree_and_branch',
        'tests/hermes_cli/test_worktree_gc.py::TestAuditVerdicts::test_unique_unpushed_commits_keep',
        'tests/hermes_cli/test_worktree_gc.py::TestAuditVerdicts::test_untracked_only_is_reap_archive',
        'tests/hermes_cli/test_worktree_gc.py::TestAuditVerdicts::test_without_a_remote_local_trunk_is_the_baseline',
        'tests/hermes_cli/test_worktree_gc.py::TestCmdWorktreeJson::test_prune_dry_run_json',
        'tests/hermes_cli/test_worktree_gc.py::TestOlderThanGate::test_aged_reapable_tree_still_reaps',
        'tests/hermes_cli/test_worktree_gc.py::TestOlderThanGate::test_young_reapable_tree_kept_under_older_than',
        'tests/hermes_cli/test_worktree_gc.py::TestReclaim::test_dead_locked_tree_is_unlocked_and_reaped',
        'tests/hermes_cli/test_worktree_gc.py::TestReclaim::test_dry_run_changes_nothing',
        'tests/hermes_cli/test_worktree_gc.py::TestReclaim::test_reap_removes_tree_and_branch',
        'tests/hermes_cli/test_worktree_gc.py::TestReclaim::test_untracked_files_archived_under_the_active_profile_home',
        'tests/hermes_platform/test_resolver_app.py::test_locate_reports_expanded_path_when_missing',
        'tests/hermes_state/test_lease_pid_namespace.py::test_flock_holder_record_qualifies_pid_namespaces',
        'tests/plugins/memory/test_byterover_multiplex_child_env.py::test_secondary_profile_child_uses_its_own_key_not_defaults',
        'tests/plugins/memory/test_holographic_profile_db_path.py::test_save_config_stores_only_this_profiles_default_path_as_the_placeholder[display]',
        'tests/pm/test_build_operations.py::test_frozen_export_preserves_git_commit_pin',
        'tests/pm/test_custom_root_union.py::test_home_layout_joins_sibling_union[default]',
        'tests/pm/test_pm_authority.py::test_failed_replacement_preserves_entry_and_facts[replacement-install-verify]',
        'tests/pm/test_pm_authority.py::test_failed_restore_preserves_both_interrupted_versions',
        'tests/pm/test_runtime_gc.py::test_lease_taken_while_a_peer_pruned_it_is_retaken',
        'tests/pm/test_runtime_gc.py::test_next_reader_removes_lease_left_by_hard_exit',
        'tests/pm/test_uv_python.py::test_copy_failure_preserves_previous_python[copy]',
        'tests/pm/test_uv_python.py::test_project_environment_replaces_generation_when_pinned_python_moves',
        'tests/pm/test_worker_registry.py::test_definition_import_failures_are_package_errors[collision]',
        'tests/pm/test_worker_registry.py::test_definition_import_failures_are_package_errors[dependency]',
        'tests/pm/test_worker_registry.py::test_definition_import_failures_are_package_errors[name]',
        'tests/pm/test_worker_registry.py::test_definition_import_failures_are_package_errors[not-class]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[0-stderr-ci]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[0-stderr-install]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[0-stdout-ci]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[0-stdout-install]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[17-stderr-ci]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[17-stderr-install]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[17-stdout-ci]',
        'tests/pm/test_workspace_output_encoding.py::test_node_sidecar_retains_output_and_exit_status[17-stdout-install]',
        'tests/scripts/desktop_update/test_desktop_update_linux_gate_arm.py::test_arch_specific_dir_is_preferred_over_a_stale_x86_64_one',
        'tests/scripts/desktop_update/test_desktop_update_linux_gate_arm.py::test_arch_specific_unpacked_dir_still_relaunches',
        'tests/scripts/desktop_update/test_desktop_update_linux_gate_arm.py::test_foreign_target_with_arm_dirs_present_is_still_skew',
        'tests/scripts/desktop_update/test_desktop_update_windows_marker.py::test_owner_creation_time_is_read_for_system_processes[False]',
        'tests/scripts/desktop_update/test_desktop_update_windows_marker.py::test_owner_creation_time_is_read_for_system_processes[True]',
        'tests/scripts/install/test_install_ps1_script_suites.py::test_suite_passes[test-install-ps1-store-guard.ps1-pwsh]',
        'tests/scripts/test_baked_bytecode.py::test_launcher_keeps_user_cache_redirect_without_marker',
        'tests/scripts/test_desktop_build_cache.py::test_composite_transports_only_and_uses_the_restore_key_for_save',
        'tests/scripts/test_desktop_build_cache.py::test_direct_snapshot_preserves_node_receipt_and_excludes_job_secrets',
        'tests/scripts/test_install_stage_frames.py::test_manifest_accepts_the_desktop_home_argument[--hermes-home]',
        'tests/scripts/test_install_stage_frames.py::test_manifest_accepts_the_desktop_home_argument[-HermesHome]',
        'tests/scripts/test_install_stage_frames.py::test_stage_result_matches_the_actual_exit[explicit-failure]',
        'tests/scripts/test_install_stage_frames.py::test_stage_result_matches_the_actual_exit[skipped]',
        'tests/scripts/test_install_stage_frames.py::test_stage_result_matches_the_actual_exit[success]',
        'tests/scripts/test_install_stage_frames.py::test_stage_result_matches_the_actual_exit[unknown]',
        'tests/scripts/test_install_stage_frames.py::test_stage_result_matches_the_actual_exit[write-failure]',
        'tests/scripts/test_release_artifacts.py::test_windows_metadata_is_read_from_package_and_stale_stamp_is_rejected',
        'tests/scripts/test_termux_build_wheels.py::test_requirement_readers_preserve_pins_and_reject_malformed_rows[/xef/xbb/xbf]',
        'tests/scripts/test_termux_build_wheels.py::test_requirement_readers_preserve_pins_and_reject_malformed_rows[]',
        'tests/test_hermes_home_profile_warning.py::TestBootReadersBeforeProfileOverride::test_scratch_export_uses_the_process_home_silently',
        'tests/test_hermes_logging.py::TestSafeStderr::test_wraps_non_utf8_stderr',
        'tests/test_hermes_logging.py::TestSetupLogging::test_out_of_band_profile_delete_releases_routed_handler[logs-only]',
        'tests/test_hermes_logging.py::TestSetupLogging::test_out_of_band_profile_delete_releases_routed_handler[rmtree]',
        'tests/test_hermes_logging.py::TestSetupLogging::test_profile_routing_falls_back_when_profile_home_deleted',
        'tests/test_hermes_logging.py::TestSetupLogging::test_setup_for_an_already_routed_home_adds_no_duplicate_writer',
        'tests/test_hermes_logging.py::test_eio_after_successful_reopen_still_names_the_path_once',
        'tests/test_hermes_logging.py::test_eio_from_file_handler_names_the_path_once_then_recovers',
        'tests/test_scratch_dir.py::test_prune_releases_git_worktree_registration_of_idle_entry',
        'tests/tools/test_bot_retry_policy.py::test_deliver_never_retries_auth_failure',
        'tests/tools/test_bot_retry_policy.py::test_deliver_retries_once_on_context_overflow',
        'tests/tools/test_bot_retry_policy.py::test_deliver_retries_same_argv_on_transient_failure',
        'tests/tools/test_bot_retry_policy.py::test_deliver_retry_reads_the_stream_the_cli_writes_and_resumes_the_persisted_row',
        'tests/tools/test_browser_use_cli.py::TestBackendSwapRetargetsDaemons::test_browser_swap_restarts_every_daemon_on_the_new_endpoint',
        'tests/tools/test_container_cwd_sanitize.py::TestFileOpsCwdSanitizedAtCallSite::test_valid_container_override_is_preserved',
        'tests/tools/test_container_cwd_sanitize.py::TestOverrideCwdSanitizedAtCallSite::test_valid_container_override_is_preserved',
        'tests/tools/test_docker_environment.py::test_reuse_environment_fingerprint_ignores_volatile_temp_mounts',
        'tests/tools/test_docker_environment.py::test_symlinked_skills_tree_reuses_container_across_processes',
        'tests/tools/test_docker_mounted_host_session_cwd.py::TestMountedHostSessionCwd::test_in_container_session_cwd_is_preserved',
        'tests/tools/test_docker_session_isolation.py::TestRecordedHostCwdDiscardedOnContainers::test_container_record_honored_for_docker',
        'tests/tools/test_file_operations.py::TestSearchFilesIncludesDirectories::test_rg_sorts_files_and_directories_before_pagination',
        'tests/tools/test_file_operations.py::TestSearchFilesIncludesDirectories::test_rg_target_files_excludes_gitignored_empty_directory',
        'tests/tools/test_file_operations.py::TestSearchFilesIncludesDirectories::test_rg_target_files_includes_matching_empty_directory',
        'tests/tools/test_hermes_subprocess_env.py::TestTierInvariants::test_left_core_secrets_stripped_without_their_plugin',
        'tests/tools/test_live_env_cwd_override_sanitize.py::test_live_env_cwd_write_is_sanitized_for_container_backends[docker-None-/workspace/task42-/workspace/task42]',
        'tests/tools/test_mcp_stability.py::TestStdioPgroupReaping::test_kill_orphaned_signals_when_start_time_matches',
        'tests/tools/test_mcp_stability.py::TestStdioPgroupReaping::test_kill_orphaned_skips_recycled_pid',
        'tests/tools/test_mcp_stability.py::TestStdioPgroupReaping::test_kill_orphaned_without_baseline_keeps_legacy_behaviour',
        'tests/tools/test_mcp_tool_issue_948.py::test_bare_launcher_commands_keep_the_managed_first_resolution',
        'tests/tools/test_mcp_tool_issue_948.py::test_bare_python3_keeps_the_managed_hit_when_the_user_has_none',
        'tests/tools/test_mcp_tool_issue_948.py::test_bare_python3_steps_past_the_managed_runtime_to_the_user_hit',
        'tests/tools/test_modal_sandbox_fixes.py::TestHostPrefixList::test_all_common_host_paths_flagged_unusable',
        'tests/tools/test_web_keyless_fallback.py::TestProviderRouting::test_keyless_disabled_falls_through_to_key_error',
        'tests/tools/test_web_keyless_fallback.py::TestProviderRouting::test_tier_paid_forces_keyed_without_key',
        'tests/tui_gateway/test_bot_relay_methods.py::test_deliver_validates_profile_and_runs_transport',
        'tests/tui_gateway/test_bot_relay_methods.py::test_reported_turn_still_lingering_at_the_cap_is_booked_from_its_latest_report_not_killed',
        'tests/tui_gateway/test_composite_carrier_rewind.py::test_prompt_row_id_rewind_preserves_scaffold_before_regeneration',
        'tests/tui_gateway/test_desktop_session_row_git_meta.py::test_first_submit_row_records_git_branch_and_root',
        'tests/tui_gateway/test_desktop_session_row_git_meta.py::test_row_git_probe_runs_once_per_session',
        'tests/tui_gateway/test_desktop_session_workspace_persistence.py::test_desktop_inherited_cwd_persists_only_when_the_resolution_adopted_it',
        'tests/tui_gateway/test_display_methods.py::test_install_sudo_card_ignores_a_client_supplied_session_id',
        'tests/tui_gateway/test_display_methods.py::test_install_worker_keeps_the_requested_profile_scope',
        'tests/tui_gateway/test_display_watch.py::test_screen_started_or_stopped_by_another_process_is_broadcast_as_status',
        'tests/tui_gateway/test_ephemeral_profile_override.py::TestBackgroundProfileOverride::test_background_binds_and_restores_profile_home',
        'tests/tui_gateway/test_ephemeral_profile_override.py::TestBackgroundProfileOverride::test_background_restores_override_on_error',
        'tests/tui_gateway/test_ephemeral_profile_override.py::TestPreviewRestartProfileOverride::test_preview_binds_and_restores_profile_home',
        'tests/tui_gateway/test_free_tier_task_done.py::test_prompt_submit_records_only_untouched_turns[steered-over-rpc]',
        'tests/tui_gateway/test_free_tier_task_done.py::test_prompt_submit_records_only_untouched_turns[typed-while-busy]',
        'tests/tui_gateway/test_free_tier_task_done.py::test_prompt_submit_records_only_untouched_turns[untouched]',
        'tests/tui_gateway/test_lazy_session_regressions.py::TestPendingTitleValueError::test_valueerror_clears_pending_title',
        'tests/tui_gateway/test_out_of_band_history_adoption.py::test_desktop_prompt_carries_gateway_rows_appended_after_hydration',
        'tests/tui_gateway/test_out_of_band_history_adoption.py::test_unstamped_desktop_prompt_does_not_adopt_its_own_user_row',
        'tests/tui_gateway/test_out_of_band_history_adoption.py::test_unstamped_prompt_after_a_foreign_compaction_sends_the_compacted_transcript',
)

ROWS: dict[str, tuple[pytest.MarkDecorator, ...]] = (
    {node: (_up_red(_REASON),) for node in _NODES} if _WIN else {}
)
