"""W0-G2 — a ``refactor(`` commit never touches an upstream file.

Plan: ``docs/agent-runtime-harness/planned/downstream-god-file-refactor.md`` §2
Wave 0 and rule 9; ``god-file-program-2026-09-24.md``'s scope rule. For every
first-parent commit after the Wave 0 landing (the commit whose subject starts
``test(tooling): W0 —``) whose subject starts ``refactor(``, the files it
changes must not meet the upstream manifest
(``tests/fixtures/upstream_manifest.txt`` — committed, so CI needs no
``upstream`` remote; regenerated by ``scripts/upstream_footprint.py
--refresh-manifest``). The logic is ``scripts/god_file_fences.py``'s
``fence_anchor`` / ``fence_violations``.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from scripts import god_file_fences as fences
from scripts import god_file_probe as probe


def _git(root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=root, capture_output=True, text=True, encoding="utf-8", check=True
    ).stdout


def test_no_refactor_commit_touches_an_upstream_file():
    root = probe.ROOT
    if _git(root, "rev-parse", "--is-shallow-repository").strip() == "true":
        pytest.skip("shallow clone: the history this gate reads is not here")
    base = fences.fence_anchor(root)
    assert base is not None, (
        f"no first-parent commit whose subject starts {fences.FENCE_ANCHOR_SUBJECT!r} — the gate has no anchor"
    )
    found = fences.fence_violations(root, probe.upstream_paths(), base)
    assert found == [], "refactor lanes stay downstream (rule 9) — file a widening row instead:\n" + "\n".join(found)


def test_the_fence_reds_a_refactor_commit_on_an_upstream_file(tmp_path):
    """Positive control: a real repo, the anchor, one fork-only refactor, then one that crosses."""

    def commit(path: str, subject: str) -> None:
        target = tmp_path / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(subject, encoding="utf-8")
        _git(tmp_path, "add", path)
        _git(tmp_path, "-c", "user.name=w0", "-c", "user.email=w0@example.invalid", "commit", "-q", "-m", subject)

    _git(tmp_path, "init", "-q")
    commit("hermes_cli/main.py", "refactor(z): before the anchor, not fenced")
    commit("tests/tooling/gate.py", f"{fences.FENCE_ANCHOR_SUBJECT} gates")
    commit("agent_runtime/x.py", "refactor(x): fork-only move")
    base = fences.fence_anchor(tmp_path)
    assert base is not None
    upstream = frozenset({"hermes_cli/main.py"})
    assert fences.fence_violations(tmp_path, upstream, base) == []
    commit("hermes_cli/main.py", "refactor(y): crosses the fence")
    found = fences.fence_violations(tmp_path, upstream, base)
    assert len(found) == 1 and found[0].endswith("touches upstream hermes_cli/main.py")
