"""Render the live Harness argparse tree without executing any command.

Run with --write to refresh the committed reference, --check to detect drift,
or no arguments to print it. Human intent/examples live in 10-command-directory.md.
Only parser declarations are consumed; no runtime snapshot, auth or handler runs.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

REFERENCE = Path("docs/agent-runtime-harness/reference/harness-commands.md")


def build_tree() -> argparse.ArgumentParser:
    from hermes_cli.harness import build_parser

    parser = argparse.ArgumentParser(prog="hermes")
    build_parser(parser.add_subparsers(dest="command", required=True))
    return parser


def command_parsers(parser, path=()):
    """Walk canonical paths once; retain aliases alongside their parser."""
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        seen = set()
        for name, child in action.choices.items():
            if id(child) in seen:
                continue
            seen.add(id(child))
            aliases = tuple(key for key, value in action.choices.items()
                            if value is child and key != name)
            child_path = (*path, name)
            yield child_path, child, aliases
            yield from command_parsers(child, child_path)


def render(parser: argparse.ArgumentParser) -> str:
    rows = list(command_parsers(parser))
    lines = [
        "# Harness command reference (generated)", "",
        "[Task-oriented command directory](../10-command-directory.md)", "",
        "Generated by `python scripts/emit_harness_command_directory.py --write`",
        "from `hermes_cli.harness.build_parser`. Do not edit this file by hand.",
        "Run `python scripts/emit_harness_command_directory.py --check` to detect drift.",
        "No command handlers are executed during generation.", "",
        "This lists parser syntax, NOT a safety classification or a promise that a",
        "command is available on the connected runtime. Read the task directory",
        "before changing state. Alias paths share the canonical command's flags.", "",
        "## Command index", "",
    ]
    for path, _, aliases in rows:
        name = "hermes " + " ".join(path)
        anchor = "-".join(("hermes", *path))
        suffix = f" — aliases: {', '.join(f'`{a}`' for a in aliases)}" if aliases else ""
        lines.append(f"- [{name}](#{anchor}){suffix}")
    for path, child, aliases in rows:
        name = "hermes " + " ".join(path)
        # Fixed width is independent of COLUMNS and the caller's terminal.
        child.formatter_class = lambda prog: argparse.HelpFormatter(prog, width=100)
        lines.extend(["", f"## {name}", ""])
        if aliases:
            lines.extend([f"Aliases: {', '.join(f'`{a}`' for a in aliases)}.", ""])
        lines.extend(["```text", child.format_help().rstrip(), "```"])
    return "\n".join(lines) + "\n"


def check_reference(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    diff = difflib.unified_diff(actual.splitlines(), expected.splitlines(),
                                fromfile=str(path), tofile="live argparse tree", lineterm="")
    print("\n".join(diff), file=sys.stderr)
    return False


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render(build_tree())
    path = REPO_ROOT / REFERENCE
    if args.check:
        return 0 if check_reference(path, expected) else 1
    if args.write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Wrote {REFERENCE}")
    else:
        sys.stdout.write(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
