#!/usr/bin/env python3
"""The fork's footprint in upstream-owned files — the ``[up-fp]`` ratchet.

A file is UPSTREAM iff its path is in the upstream manifest
(``tests/fixtures/upstream_manifest.txt``: ``git ls-tree -r --name-only`` of
the merge base UNION ``upstream/main``, first line ``# base <sha>``). The footprint is the fork's diff
from that base to the working tree, restricted to the manifest:

  files          upstream files with any diff against the base
  deleted_lines  sum of deletions in those files (the conflict generators)
  heavy          those with added + deleted > HEAVY_THRESHOLD

  python scripts/upstream_footprint.py                  # the [up-fp] line
  python scripts/upstream_footprint.py --json           # per-file rows
  python scripts/upstream_footprint.py --ledger <md>    # write / merge the ledger
  python scripts/upstream_footprint.py --refresh-manifest   # needs the upstream remote

CI has no ``upstream`` remote, which is why the manifest is committed and read
from disk. ``tests/scripts/test_upstream_footprint.py`` holds the three numbers
to ``tests/fixtures/upstream_footprint.json`` in both directions: they may never
rise, and the fixture must follow them down. Plan:
``docs/agent-runtime-harness/planned/harness-plugin-and-upstream-seams.md`` §1 rule 2.

Subprocess git only; the counting is a pure function over numstat text.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tests" / "fixtures" / "upstream_manifest.txt"
DEFAULT_LEDGER = ROOT / "docs" / "agent-runtime-harness" / "planned" / "upstream-footprint-ledger.md"
HEAVY_THRESHOLD = 200
UPSTREAM_REF = "upstream/main"

LEDGER_COLUMNS = ("path", "added", "deleted", "disposition", "reason", "stage")
#: ``carry-permanent`` is a ``carry`` the operator has RULED permanent (plan §1 rule 6):
#: still counted in ``files=`` (it is still an edit to an upstream file), settled for
#: the detach read (``files=0`` or only ruled rows).
DISPOSITIONS = ("upstream", "hook", "carry", "carry-permanent")
#: Plan §1 rule 7: nothing under these trees may be ``carry-permanent`` — it
#: moves to a fork-only file, hooks through a widening, or is adopted.
NEVER_PERMANENT_PREFIXES = ("agent/", "tools/", "gateway/", "hermes_cli/")
NEW_ROW_DEFAULTS = {"disposition": "carry", "reason": "unreviewed", "stage": "-"}
LEDGER_PREAMBLE = """# Upstream footprint ledger — one row per upstream file the fork edits

Generated by `scripts/upstream_footprint.py --ledger`; `added` / `deleted` are rewritten on
every run, `disposition` / `reason` / `stage` are hand-edited and survive regeneration (the
merge is on `path`). A new row arrives as `carry` / `unreviewed` / `-`. Dispositions are the
plan's three: `upstream`, `hook`, `carry` (§1 rule 1 of
[`harness-plugin-and-upstream-seams.md`](harness-plugin-and-upstream-seams.md)), plus
`carry-permanent`: a carry the operator has ruled permanent (§1 rule 6), still counted in
`files=`, settled for the detach read.

"""


@dataclass(frozen=True)
class FileDelta:
    path: str
    added: int
    deleted: int
    heavy: bool


@dataclass(frozen=True)
class Footprint:
    files: int
    deleted_lines: int
    heavy: int
    rows: tuple[FileDelta, ...]

    def line(self) -> str:
        return f"[up-fp] files={self.files} deleted_lines={self.deleted_lines} heavy={self.heavy}"


# --------------------------------------------------------------------------- pure


def parse_numstat(text: str) -> list[tuple[str, int, int]]:
    """``git diff --numstat --no-renames`` output → ``(path, added, deleted)``.

    Accepts both the ``-z`` form (NUL-terminated records) and the plain
    newline form. A binary file (``-``/``-``) counts as 0/0 — it is still a
    touched file.
    """
    records = text.split("\0") if "\0" in text else text.splitlines()
    out: list[tuple[str, int, int]] = []
    for record in records:
        record = record.strip("\n")
        if not record:
            continue
        added, deleted, path = record.split("\t", 2)
        out.append((path, 0 if added == "-" else int(added), 0 if deleted == "-" else int(deleted)))
    return out


def count_footprint(numstat_text: str, manifest: Iterable[str], *, heavy_threshold: int = HEAVY_THRESHOLD) -> Footprint:
    """The three ratchet numbers over numstat text, restricted to ``manifest``."""
    upstream = set(manifest)
    rows = tuple(
        sorted(
            (
                FileDelta(path, added, deleted, added + deleted > heavy_threshold)
                for path, added, deleted in parse_numstat(numstat_text)
                if path in upstream
            ),
            key=lambda row: row.path,
        )
    )
    return Footprint(
        files=len(rows),
        deleted_lines=sum(row.deleted for row in rows),
        heavy=sum(1 for row in rows if row.heavy),
        rows=rows,
    )


def parse_manifest(text: str) -> tuple[str | None, list[str]]:
    """Manifest text → ``(base, paths)``; ``base`` from the ``# base <sha>`` header."""
    base = None
    paths: list[str] = []
    for line in text.splitlines():
        if line.startswith("#"):
            match = re.match(r"#\s*base\s+([0-9a-fA-F]+)", line)
            if match and base is None:
                base = match.group(1)
            continue
        if line:
            paths.append(line)
    return base, paths


def _split_row(line: str) -> list[str]:
    cells = re.split(r"(?<!\\)\|", line.strip())
    if cells and cells[0] == "":
        cells = cells[1:]
    if cells and cells[-1] == "":
        cells = cells[:-1]
    return [cell.strip().replace("\\|", "|") for cell in cells]


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|")


def ledger_rows(text: str) -> dict[str, dict[str, str]]:
    """Ledger markdown → ``{path: {column: cell}}`` for the first table's rows."""
    rows: dict[str, dict[str, str]] = {}
    header: list[str] | None = None
    for line in text.splitlines():
        if not line.lstrip().startswith("|"):
            if rows:
                break
            continue
        cells = _split_row(line)
        if header is None:
            if cells[:1] == ["path"]:
                header = cells
            continue
        if set("".join(cells)) <= set("-: "):
            continue
        row = dict(zip(header, cells))
        path = row.get("path", "").strip("`")
        if path:
            rows[path] = row
    return rows


def unknown_dispositions(text: str) -> dict[str, str]:
    """``{path: disposition}`` for every ledger row outside :data:`DISPOSITIONS`."""
    return {
        path: row.get("disposition", "")
        for path, row in ledger_rows(text).items()
        if row.get("disposition", "") not in DISPOSITIONS
    }


def forbidden_permanent(text: str) -> list[str]:
    """Paths ruled ``carry-permanent`` under a :data:`NEVER_PERMANENT_PREFIXES` tree."""
    return sorted(
        path
        for path, row in ledger_rows(text).items()
        if row.get("disposition") == "carry-permanent" and path.startswith(NEVER_PERMANENT_PREFIXES)
    )


def merge_ledger(existing: str | None, footprint: Footprint) -> str:
    """Rewrite the ledger table for ``footprint``, keeping hand-edited columns by path.

    Text before the table (and after it) is kept verbatim; a path no longer in
    the footprint loses its row, because the fork no longer edits that file.
    """
    head, tail = LEDGER_PREAMBLE, ""
    kept: dict[str, dict[str, str]] = {}
    if existing:
        lines = existing.splitlines(keepends=True)
        start = next(
            (i for i, line in enumerate(lines) if _split_row(line)[:1] == ["path"] and line.lstrip().startswith("|")),
            None,
        )
        if start is None:
            head = existing if existing.endswith("\n") else existing + "\n"
        else:
            end = start
            while end < len(lines) and lines[end].lstrip().startswith("|"):
                end += 1
            head, tail = "".join(lines[:start]), "".join(lines[end:])
            header = _split_row(lines[start])
            for line in lines[start + 2 : end]:
                cells = dict(zip(header, _split_row(line)))
                path = cells.get("path", "").strip("`")
                if path:
                    kept[path] = cells
    body = [
        "| " + " | ".join(LEDGER_COLUMNS) + " |\n",
        "|" + "|".join("---" for _ in LEDGER_COLUMNS) + "|\n",
    ]
    for row in footprint.rows:
        old = kept.get(row.path, {})
        hand = {key: old.get(key) or default for key, default in NEW_ROW_DEFAULTS.items()}
        body.append(
            "| "
            + " | ".join(
                [f"`{_cell(row.path)}`", str(row.added), str(row.deleted), _cell(hand["disposition"]), _cell(hand["reason"]), _cell(hand["stage"])]
            )
            + " |\n"
        )
    return head + "".join(body) + tail


# --------------------------------------------------------------------------- git


def _git(*args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(ROOT), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="surrogateescape",
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(f"[up-fp] git {' '.join(args)} failed ({result.returncode}): {result.stderr.strip()}")
    return result.stdout


def read_manifest(path: Path = MANIFEST) -> tuple[str | None, list[str]]:
    return parse_manifest(path.read_text(encoding="utf-8"))


def measure(base: str | None = None, manifest_path: Path = MANIFEST) -> tuple[str, Footprint]:
    """The footprint of the working tree against ``base`` (default: the manifest's)."""
    manifest_base, paths = read_manifest(manifest_path)
    base = base or manifest_base
    if not base:
        raise SystemExit(f"[up-fp] no --base given and {manifest_path} carries no '# base <sha>' header")
    numstat = _git("-c", "core.quotepath=off", "diff", "--numstat", "-z", "--no-renames", base)
    return base, count_footprint(numstat, paths)


def manifest_paths(base_listing: str, tip_listing: str) -> list[str]:
    """Upstream-owned paths: the merge base's tree UNION upstream's tip.

    The footprint diffs from the BASE, so a file the base has is upstream's even
    when upstream deleted it after the base: a fork edit to it is a modify/delete
    conflict at the next merge and must stay counted. The tip adds files upstream
    created since the base (an add/add conflict with a fork file of that name).
    """
    return sorted({path for listing in (base_listing, tip_listing) for path in listing.split("\0") if path})


def refresh_manifest(manifest_path: Path = MANIFEST) -> str:
    base = _git("merge-base", "HEAD", UPSTREAM_REF).strip()[:10]
    ls_tree = ("-c", "core.quotepath=off", "ls-tree", "-r", "-z", "--name-only")
    paths = manifest_paths(_git(*ls_tree, base), _git(*ls_tree, UPSTREAM_REF))
    manifest_path.write_text(f"# base {base}\n" + "\n".join(paths) + "\n", encoding="utf-8", newline="\n")
    return base


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--base", help="merge base to diff from (default: the manifest header's base)")
    parser.add_argument("--json", action="store_true", help="emit per-file rows {path, added, deleted, heavy}")
    parser.add_argument("--ledger", nargs="?", const=str(DEFAULT_LEDGER), help="write/merge the ledger markdown")
    parser.add_argument("--refresh-manifest", action="store_true", help=f"regenerate the manifest from {UPSTREAM_REF}")
    args = parser.parse_args(argv)

    if args.refresh_manifest:
        print(f"[up-fp] manifest refreshed at base {refresh_manifest()}")
    _, footprint = measure(args.base)
    if args.json:
        print(json.dumps([asdict(row) for row in footprint.rows], indent=2))
    if args.ledger:
        ledger = Path(args.ledger)
        existing = ledger.read_text(encoding="utf-8") if ledger.exists() else None
        merged = merge_ledger(existing, footprint)
        ledger.write_text(merged, encoding="utf-8", newline="\n")
        ruled = sum(1 for row in ledger_rows(merged).values() if row.get("disposition") == "carry-permanent")
        print(f"[up-fp] ledger: carry-permanent={ruled} of files={footprint.files}")
    if not args.json:
        print(footprint.line())
    return 0


if __name__ == "__main__":
    sys.exit(main())
